name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - macos-latest
#          - windows-latest
        python-version:
#          - "3.7"
          - "3.8"
#          - "3.9"
#          - "3.10"
#          - "3.11-dev"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install xonsh shell
      run: pip install xonsh
    - name: Install prompt-toolkit
      run: pip install prompt-toolkit
    - name: Install packaging
      run: pip install packaging
    - name: Install xontrib
      run: pip install .
    - name: Test
      run: xonsh -c 'xontrib load oh_my_xonsh'
